trigger:
- main

pool:
  name: WindowsAgent

stages:
- stage: TerraformPlan
  jobs:
  - job: TerraformPlanJob
    steps:
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
      displayName: 'Use Terraform latest'
      inputs:
        terraformVersion: '1.3.5'  # specify the version here
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : azurerm'
      inputs:
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'deploy-Vm'
        backendAzureRmResourceGroupName: 'Safi_rg'
        backendAzureRmStorageAccountName: tfstatefilessacloud
        backendAzureRmContainerName: tfstatefile
        backendAzureRmKey: terraform.tfstatefile
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : azurerm'
      inputs:
        command: plan
        environmentServiceNameAzureRM: 'deploy-Vm'
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false

- stage: ManualApproval
  dependsOn: TerraformPlan
  jobs:
  - deployment: ManualApprovalDeployment
    environment: 'ApprovalEnv'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Manual approval required before applying Terraform changes."
            displayName: 'Awaiting Manual Approval'

- stage: TerraformApply
  dependsOn: ManualApproval
  jobs:
  - job: TerraformApplyJob
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : azurerm'
      inputs:
        command: apply
        environmentServiceNameAzureRM: 'deploy-Vm'
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false
