trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'deploy-Vm'
    backendAzureRmResourceGroupName: 'Safi_rg'
    backendAzureRmStorageAccountName: 'tfstatefilessacloud'
    backendAzureRmContainerName: 'tfstatefile'
    backendAzureRmKey: 'terraform.tfstatefile'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'deploy-Vm'
