trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install-Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: Initialize-Provider
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'deploy-Vm'
        backendAzureRmResourceGroupName: 'Safi_rg'
        backendAzureRmStorageAccountName: 'tfstatefilessacloud'
        backendAzureRmContainerName: 'tfstatefile'
        backendAzureRmKey: 'terraform.tfstatefile'
    - task: TerraformTaskV4@4
      displayName: Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'deploy-Vm'
    - script: ls -la $(Build.ArtifactStagingDirectory)
      displayName: 'List files in staging directory'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/artifacts.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)/artifacts.zip'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployToProduction
    displayName: 'Deploy to Production'
    environment: 'Approvers' # Reference to the environment with the approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/artifacts.zip'
              destinationFolder: '$(Pipeline.Workspace)/extracted'
          - task: TerraformTaskV4@4
            displayName: Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'deploy-Vm'
              commandOptions: '$(Pipeline.Workspace)/extracted'
